### ISSUE TITLE
Support actions/upload-artifact@v4

### ISSUE THREAD

**Issue by esev** [sigstore/gh-action-sigstore-python#100]
**Description**

actions/upload-artifact@v3 does not seem to be compatible with actions/download-artifact@v4. https://github.com/actions/download-artifact?tab=readme-ov-file#breaking-changes

It would be helpful if there was a version of gh-action-sigstore-python that was (optionally?) compatible with actions/download-artifact@v4.

**Comment by woodruffw** [comment]
Yeah, requiring `>= 4` makes sense to me. And +1 to mentioning it in the release notes.

> We should also add a dependabot config to make these update PRs

I'll do this today.

**Comment by woodruffw** [comment]
#101 adds a dependabot config.

**Comment by woodruffw** [comment]
#101 and #102 have been merged, meaning that `@v4` is now supported on `main`. I've done a prerelease to confirm that it works, and we'll likely ship this with the next minor release (with a notice in the release notes about breakage with `@v3`).
