### ISSUE TITLE
Add more self tests to CI

### ISSUE THREAD

**Issue by tetsuo-cpp** [sigstore/gh-action-sigstore-python#2]
Let's add more invocations of `sigstore-python` that exercise the different CLI options. At the moment, we just sign `./tests/artifact.txt` in the prod and staging instances.

**Comment by woodruffw** [comment]
I added some "xfail" style tests with #37, and we should probably add some more (at least one for each invocation of `_fatal_help` in the action).

**Comment by woodruffw** [comment]
I think we can consider this complete for now -- there are a handful of settings that we don't explicitly test (like the `fulcio-url` and `rekor-url` settings), but these map directly to their `sigstore` CLI equivalents.
