### ISSUE TITLE
Flip the `release-signing-artifacts` default

### ISSUE THREAD

**Issue by woodruffw** [sigstore/gh-action-sigstore-python#45]
This is currently `false` by default, but arguably it should be `true`: a user who uses this action in the context of a `release: published` event is probably expecting their signatures to be uploaded to the release, and shouldn't have to explicitly opt into it.

**Comment by stevenh** [comment]
Related issue https://github.com/sigstore/gh-action-sigstore-python/issues/99 to be considered before switch the default.
